### ISSUE TITLE
Unexpected Repository Included

### ISSUE THREAD

**Issue by 0x4007** [devpool-directory/devpool-directory-tasks#10]
This isn't inside of the `projects.json` list so I'm not sure how it got in the directory.

- https://github.com/ubiquity/devpool-directory/issues/734

This should be diagnosed and fixed.

**Comment by devpanther** [comment]
I think there is a branch for adding `card-issuance` but it was not merged
https://github.com/ubiquity/devpool-directory/tree/add-ubiquity-card-issuance

**Comment by 0x4007** [comment]
> I think there is a branch for adding `card-issuance` but it was not merged
> https://github.com/ubiquity/devpool-directory/tree/add-ubiquity-card-issuance

Great observation. That seems extremely likely to be related to the issue.

**Comment by devpanther** [comment]
> > I think there is a branch for adding `card-issuance` but it was not merged
> > https://github.com/ubiquity/devpool-directory/tree/add-ubiquity-card-issuance
> 
> Great observation. That seems extremely likely to be related to the issue.

How is the dev pool directory code hosted, I think the problem is it runs all branches.

The last time the PR was live was 3 weeks ago, exactly when the card-issuance found its way in and after it was closed, it never happened again.

**Comment by devpanther** [comment]
https://github.com/ubiquity/ubiquibot/pull/295 Introduced `Auto devpool PR on installation` and I think it works but now the hosting service seems to be running codes from every branch created..

I am trying to reproduce the creation of PR

**Comment by devpanther** [comment]
But i cannot reproduce because there is a bug now

https://github.com/ubiquity/devpool was changed to https://github.com/ubiquity/devpool-directory somehow and wasn't changed here https://github.com/seprintour/bounty-bot/blob/5eaad6200071349772c7f777f72f346abb99044f/src/handlers/pull-request/create-devpool-pr.ts#L11

@pavlovcik
