### ISSUE TITLE
Delete Unavailable Tasks From Twitter

### ISSUE THREAD

**Issue by 0x4007** [devpool-directory/devpool-directory-tasks#13]
Delete tweets for tasks that are assigned or closed!

>> Just newly posted ones should be tweeted.

> Should we delete a tweet if an issue was closed?

_Originally posted by @rndquu in https://github.com/ubiquity/devpool-directory/pull/1023#issuecomment-1909430199_

**Comment by fpearlf** [comment]
I would love to hack on this

**Comment by 0x4007** [comment]
I think this might be more difficult to work on because tweeting hasn't been implemented yet. 

Anyways think through the implementation based on the current state of the code if you want to take this on.

**Comment by rndquu** [comment]
> I would love to hack on this

You may take https://github.com/ubiquity/devpool-directory-bounties/issues/12 or https://github.com/ubiquity/devpool-directory-bounties/issues/1 first and make sure github issues are posted in a twitter account

Then we could get back to the current issue with deleting tweets for closed issues

**Comment by 0x4007** [comment]
Here is my current Twitter implementation. I just didn't merge it because I was unable to test it (its pretty tedious to get an API key for Twitter.) We just need to confirm the code works before merging! After that, I imagine that we will need to implement a Tweet search and match the URLs as keys in order to select and delete. 

https://github.com/ubiquity/devpool-directory/pull/1023/files

**Comment by BeanieMen** [comment]
Why wasn't this bounty created in the Directory

**Comment by 0x4007** [comment]
> Why wasn't this bounty created in the Directory

https://github.com/ubiquity/devpool-directory-bounties/blob/development/README.md
