### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by rndquu** [devpool-directory/devpool-directory-tasks#14]
What should be done:
1. Cover https://github.com/ubiquity/devpool-directory/blob/8bb4d3b60804a1433c7b09b1bb83e43dd04b3b49/index.ts with tests (refactor code if necessary)
2. Setup CI to run unit tests on any PR and push to the `development` branch

**Comment by pavlovcik** [comment]
> ```diff
> + Evaluating results. Please wait...
> ```
> 

Looks like it's still unstable at times. I'll try again.

**Comment by 0x4007** [comment]
> ```diff
> + Evaluating results. Please wait...
> ```

I can manually pay out for the assignee (200 USD) https://gnosisscan.io/tx/0x090ed3c34a0cbecbf5cb87d2aa69fffb484551fed1db8f94ff6517f7ee255703

@FernandVEYRIER if you want the comment incentives as well, we will need to fix where it crashed first. 

https://github.com/ubiquibot/comment-incentives/actions/runs/7881915632/job/21506313614#step:5:75

https://github.com/ubiquibot/comment-incentives/blob/626aed050d2040e389608851de73481abb3fd017/src/index.ts#L166

**Comment by gentlementlegen** [comment]
@pavlovcik Yes sure I could have a look. Is there any issue for this matter, should something be created about it?

**Comment by 0x4007** [comment]
@FernandVEYRIER Looks like there is some type of edge case with the bot failing to display the conversation incentives by trying to parse My quote comment with "evaluating results"'s embedded metadata (we use HTML commenting to embed a JSON object of metadata for bot comments to inter operate with other bot plugins (standardized way for information to be shared about bot comments)

I'll have to regenerate and try again after deleting the offending comments.

**Comment by 0x4007** [comment]
@FernandVEYRIER I guess it goes without saying that you shouldn't claim this one (I rotated the keys last week so I don't have the ability to invalidate on my phone now cause I forgot to import it)

**Comment by 0x4007** [comment]
@FernandVEYRIER looks like there's some issue with the implementation 

More details are here: https://github.com/ubiquity/devpool-directory/pull/1087#discussion_r1501914353

Can you look into this?

**Comment by gentlementlegen** [comment]
@pavlovcik Will have a look!

**Comment by 0x4007** [comment]
I think just change the wording of the test or remove it so that it is not ambiguous for future reviewers.

**Comment by gentlementlegen** [comment]
@pavlovcik should I open a PR that links again the this issue for the fix?

**Comment by rndquu** [comment]
> @pavlovcik should I open a PR that links again the this issue for the fix?

You mean the PR for the fix mentioned here https://github.com/ubiquity/devpool-directory/pull/1087#discussion_r1501914353 ?

Since unit tests (1st iteration) are implemented it makes sense to open a PR without mentioning current issue, but I'm not sure if there is any special logic on the bot's side for such cases (when issue is reopened)

**Comment by 0x4007** [comment]
No special logic (I.e. penalties) is active now so it's fine.
