### ISSUE TITLE
Total Rewards Available

### ISSUE THREAD

**Issue by 0x4007** [devpool-directory/devpool-directory-tasks#18]
It would be great for marketing purposes to tally up the total amount of rewards we have available at any given moment by looking up all of the open issues and summing the prices. 

I'm not sure where is the best place to write this information (perhaps just a simple text file in the repository somewhere) but it is important that we have access to this number from our home page at ubq.fi via a simple fetch request.

---

Inspired by https://x.com/ljxie/status/1753615859623321842?s=46&t=bdMjuqzO5LYxLUsloRROxQ

**Comment by guha-rahul** [comment]
hey @pavlovcik , since the task was of <2hours, and 13 hours have passed from the assignee. Can i take this up?

**Comment by 0x4007** [comment]
We allow for a few days grace period for deliverables to be turned around.

**Comment by devpanther** [comment]
@pavlovcik ready to review.. added QA

**Comment by devpanther** [comment]
total rewards: https://github.com/ubiquity/devpool-directory/blob/development/total-rewards.txt

**Comment by devpanther** [comment]
@pavlovcik I just noticed an issue, sync issues run every time there is a push to development.. because there is a push to update rewards, its stuck in an infinite loop

**Comment by devpanther** [comment]
I think that can be fixed by ignoring the workflow if its the reward file been pushed

**Comment by 0x4007** [comment]
Sure it's a good idea that you open a pull asap!

**Comment by 0x4007** [comment]
> 
>   <details>
>     <summary>
>       <b
>         ><h3>
>           <a
>             href="https://pay.ubq.fi/?claim=W3sidHlwZSI6ImVyYzIwLXBlcm1pdCIsInBlcm1pdCI6eyJwZXJtaXR0ZWQiOnsidG9rZW4iOiIweGU5MUQxNTNFMGI0MTUxOEEyQ2U4RGQzRDc5NDRGYTg2MzQ2M2E5N2QiLCJhbW91bnQiOiIyMjIwMDAwMDAwMDAwMDAwMDAwMCJ9LCJub25jZSI6IjQ1ODQ1OTQ0NTE3NTgyNDI4NDg0NDkxMjE2MzU3ODg4MTU2Njg2NjEwMTYzMzkzMjkxMjc0MzI0MjUyNTU0MTk4Mzk0ODkzODEzMTQwIiwiZGVhZGxpbmUiOiIxMTU3OTIwODkyMzczMTYxOTU0MjM1NzA5ODUwMDg2ODc5MDc4NTMyNjk5ODQ2NjU2NDA1NjQwMzk0NTc1ODQwMDc5MTMxMjk2Mzk5MzUifSwidHJhbnNmZXJEZXRhaWxzIjp7InRvIjoiMHg0MDA3Q0UyMDgzYzdGM0UxODA5N2FlQjNBMzliYjhlQzE0OWEzNDFkIiwicmVxdWVzdGVkQW1vdW50IjoiMjIyMDAwMDAwMDAwMDAwMDAwMDAifSwib3duZXIiOiIweDQ0Q2ExNURiMTAxZkQxYzE5NDQ2N0RiNkFGMGM2N0M2QmJGNEFCNTEiLCJzaWduYXR1cmUiOiIweGQwNWQzZjRkODdjNTEyNTUzOWRlNTMyYTA5MjM1ZmYzMjBlYmQ4NjEwMjk2MzQ3MjM5YmE0MTFiODU0NTEwZjgxMWE0NDYzNmJjNTk0ZTFiYWMwMGNiNzMyMDRlNWE3ODhmMGU4OWUyYjM0YmE1ZTFhOTJmYmJiNTZlYTMyOTlhMWIiLCJuZXR3b3JrSWQiOjEwMH1d"
>           >
>             [ 22.2 WXDAI ]</a
>           >
>         </h3>
>         <h6>@pavlovcik</h6></b
>       >
>     </summary>
>     <h6>Contributions Overview</h6>
> <table><thead>
> <tr><th>View</th><th>Contribution</th><th>Count</th><th>Reward</th>
> </thead><tbody>
> <tr><td>Issue</td><td>Specification</td><td>1</td><td>19.4</td></tr>
> <tr><td>Issue</td><td>Comment</td><td>1</td><td>2.8</td></tr>
> </tbody></table>
>     <h6>Conversation Incentives</h6><table><thead><tr><th>Comment</th><th>Formatting</th><th>Relevance</th><th>Reward</th></tr></thead><tbody><tr><td><h6><a href="https://github.com/ubiquity/devpool-directory-bounties/issues/18">It would be great for marketing purposes to tally up the total a...</a></h6></td><td><details><summary>19.4</summary>
> <pre>hr:
>   count: 1
>   score: "1"
>   words: 0
> </pre>
> </details></td><td>1</td><td>19.4</td></tr><tr><td><h6><a href="https://github.com/ubiquity/devpool-directory-bounties/issues/18#issuecomment-1962407497">We allow for a few days grace period for deliverables to be turn...</a></h6></td><td>2.8</td><td>0.13</td><td>2.8</td></tr></tbody></table>
>   </details>
>   
> 
>   <details>
>     <summary>
>       <b
>         ><h3>
>           <a
>             href="https://pay.ubq.fi/?claim=W3sidHlwZSI6ImVyYzIwLXBlcm1pdCIsInBlcm1pdCI6eyJwZXJtaXR0ZWQiOnsidG9rZW4iOiIweGU5MUQxNTNFMGI0MTUxOEEyQ2U4RGQzRDc5NDRGYTg2MzQ2M2E5N2QiLCJhbW91bnQiOiIxMDA2MDAwMDAwMDAwMDAwMDAwMDAifSwibm9uY2UiOiI0NTM4ODg0NDI1MDczNTczMDM1OTk5MjMyMDUzNzMzNzEzNjM1MTQ3OTk3NTM4NjE5MjY3MzM2Nzg4NzY0OTYyNDcxOTk5ODM3Nzk1MiIsImRlYWRsaW5lIjoiMTE1NzkyMDg5MjM3MzE2MTk1NDIzNTcwOTg1MDA4Njg3OTA3ODUzMjY5OTg0NjY1NjQwNTY0MDM5NDU3NTg0MDA3OTEzMTI5NjM5OTM1In0sInRyYW5zZmVyRGV0YWlscyI6eyJ0byI6IjB4Zjc2RjFBQ0I2NjAyMGY4OTNjOTUzNzFmNzQwNTQ5RjMxMkRFQTNmMSIsInJlcXVlc3RlZEFtb3VudCI6IjEwMDYwMDAwMDAwMDAwMDAwMDAwMCJ9LCJvd25lciI6IjB4NDRDYTE1RGIxMDFmRDFjMTk0NDY3RGI2QUYwYzY3QzZCYkY0QUI1MSIsInNpZ25hdHVyZSI6IjB4NTVkMzZmNDBmZjg4NmRiZjRhYmI3ZGNmYzM4ZDIxOTgzM2NlNGFkZDIyYjUyMGMyMzg4MTk2YjkzYThjZjVlNDdjYmQ1NzBkMDRlNjY3MTAzNThjZDY1MzAyY2NiZjQwMjQ3YzAyN2VhZTA3NzZkZjY2OTFkNjdiZDJhMjM2YzExYyIsIm5ldHdvcmtJZCI6MTAwfV0%3D"
>           >
>             [ 100.6 WXDAI ]</a
>           >
>         </h3>
>         <h6>@devpanther</h6></b
>       >
>     </summary>
>     <h6>Contributions Overview</h6>
> <table><thead>
> <tr><th>View</th><th>Contribution</th><th>Count</th><th>Reward</th>
> </thead><tbody>
> <tr><td>Issue</td><td>Task</td><td>1</td><td>100</td></tr>
> <tr><td>Issue</td><td>Comment</td><td>1</td><td>0</td></tr>
> <tr><td>Issue</td><td>Comment</td><td>1</td><td>0.6</td></tr>
> </tbody></table>
>     <h6>Conversation Incentives</h6><table><thead><tr><th>Comment</th><th>Formatting</th><th>Relevance</th><th>Reward</th></tr></thead><tbody><tr><td><h6><a href="https://github.com/ubiquity/devpool-directory-bounties/issues/18#issuecomment-1963051337">@pavlovcik ready to review.. added QA...</a></h6></td><td>-</td><td>0.02</td><td>-</td></tr><tr><td><h6><a href="https://github.com/ubiquity/devpool-directory-bounties/issues/18#issuecomment-1963051337">@pavlovcik ready to review.. added QA...</a></h6></td><td>0.6</td><td>0.02</td><td>0.6</td></tr></tbody></table>
>   </details>
>   
> 
>   <details>
>     <summary>
>       <b
>         ><h3>
>           <a
>             href="https://pay.ubq.fi/?claim=W3sidHlwZSI6ImVyYzIwLXBlcm1pdCIsInBlcm1pdCI6eyJwZXJtaXR0ZWQiOnsidG9rZW4iOiIweGU5MUQxNTNFMGI0MTUxOEEyQ2U4RGQzRDc5NDRGYTg2MzQ2M2E5N2QiLCJhbW91bnQiOiIyMTAwMDAwMDAwMDAwMDAwMDAwIn0sIm5vbmNlIjoiMjAzMDY4ODc1MDM4MzMwNDg5NTA5MzUwODc3NTg2NzgyOTY5MzUxNjU2NTQzOTQ1OTcxNjMxMzMwNjg2MDE3MTA5OTk0MDY5Mjg1NjIiLCJkZWFkbGluZSI6IjExNTc5MjA4OTIzNzMxNjE5NTQyMzU3MDk4NTAwODY4NzkwNzg1MzI2OTk4NDY2NTY0MDU2NDAzOTQ1NzU4NDAwNzkxMzEyOTYzOTkzNSJ9LCJ0cmFuc2ZlckRldGFpbHMiOnsidG8iOiIweDhmOTZiMDYzREUwRUM3MkFlZDE2MkRkMjdhZUNkQzk2OTllMTAwRUYiLCJyZXF1ZXN0ZWRBbW91bnQiOiIyMTAwMDAwMDAwMDAwMDAwMDAwIn0sIm93bmVyIjoiMHg0NENhMTVEYjEwMWZEMWMxOTQ0NjdEYjZBRjBjNjdDNkJiRjRBQjUxIiwic2lnbmF0dXJlIjoiMHg2NzQ3ODE5Zjk1ZDlkMGExNTQwMDg0ZDVmYTJlMmUzZTg4NmJlODU5ZWI5N2M0NGFiMjY1YmMyZDcwY2FiZWM1NWVjYTEyNzEyZGRlNDUwZmEyZDhlMmE5ZjE4N2Y3ZGY3ZjQ1M2YyZmZmZDgzMmEyYzJlNjQ0MGM0YWYwYTY2MjFiIiwibmV0d29ya0lkIjoxMDB9XQ%3D%3D"
>           >
>             [ 2.1 WXDAI ]</a
>           >
>         </h3>
>         <h6>@guha-rahul</h6></b
>       >
>     </summary>
>     <h6>Contributions Overview</h6>
> <table><thead>
> <tr><th>View</th><th>Contribution</th><th>Count</th><th>Reward</th>
> </thead><tbody>
> <tr><td>Issue</td><td>Comment</td><td>1</td><td>2.1</td></tr>
> </tbody></table>
>     <h6>Conversation Incentives</h6><table><thead><tr><th>Comment</th><th>Formatting</th><th>Relevance</th><th>Reward</th></tr></thead><tbody><tr><td><h6><a href="https://github.com/ubiquity/devpool-directory-bounties/issues/18#issuecomment-1962355347">hey @pavlovcik , since the task was of <2hours, and 13 hours hav...</a></h6></td><td>2.1</td><td>0.19</td><td>2.1</td></tr></tbody></table>
>   </details>
>   
> 

Very weird that it didn't read from the pull request.

**Comment by devpanther** [comment]
@pavlovcik I have an hotfix ready

https://github.com/ubiquity/devpool-directory/pull/1089
