### ISSUE TITLE
Statistics

### ISSUE THREAD

**Issue by 0x4007** [devpool-directory/devpool-directory-tasks#19]
I just realized that if we remove the assigned tasks, then it messes with the stats. How can we preserve the stats for marketing purposes? It would be great to write a JSON object with the following:
```typescript
type Statistics = {
  rewards: {
    notAssigned: number;
    assigned: number;
    completed: number;
    total: number;
  },
  tasks: {
    notAssigned: number;
    assigned: number;
    completed: number;
    total: number;
  }
}
```

Perhaps this feature needs to be reimplemented? Its already in use on ubq.fi and I have ideas for how to use it on Twitter too.

_Originally posted by @pavlovcik in https://github.com/ubiquity/devpool-directory/pull/1102#discussion_r1516366949_

**Comment by devpanther** [comment]
I thought about using a json instead of a text too, but I saw you have the `rewards` object and the `task`

What's the difference

**Comment by 0x4007** [comment]
> I thought about using a json instead of a text too, but I saw you have the `rewards` object and the `task`
> 
> What's the difference

One is referring to the dollar amount, one is referring to the amount of issues.
