### ISSUE TITLE
Add project category label

### ISSUE THREAD

**Issue by rndquu** [devpool-directory/devpool-directory-tasks#2]
What should be done:
1. Partner should be able to add a `category` field to his project [here](https://github.com/ubiquity/devpool-directory/blob/development/projects.json)
2. If a new issue is created from a partner's repository then if the `category` field exists then it should be added as a label to the issue

Don't forget to handle edge cases: 
1. If partner already has "synced" issues in the https://github.com/ubiquity/devpool-directory/issues those issues should also be labeled with the `category` field.
2. If the `category` field is updated or deleted the partner's issues "category" label should also be updated 
3. The `category` field can be empty (not set)

### Discussed in https://github.com/ubiquity/devpool-directory/discussions/476

<div type='discussions-op-text'>

<sup>Originally posted by **pavlovcik** May  1, 2023</sup>
We started experimenting with using the DevPool system for roles beyond software development. 

- https://github.com/ubiquity/grants is a good example of our initiative for grant writing. 

- We also have a miscellaneous tasks repo at https://github.com/ubiquity/.github 

Perhaps in the pull request to monitor the repository, we should add a property, e.g. "category" that will automatically tag those issues with a certain customizable label. 

For every repository added so far, the category can be "Development". Perhaps we could also populate all of the extra labels for extra metadata as we sometimes label bounties as "CI/CD" or "Solidity" or "UI/UX"

---

Ultimately we want to allow non developers to contribute to DAOs and I think we might be able to get it to work with this current infrastructure. </div>

**Comment by gitcoindev** [comment]
I was able to set up bounties directory in my forked org today.  I am still testing edge cases, add a readme and will open a PR soon.

**Comment by gitcoindev** [comment]
I opened a pull request and disabled actions on my fork not to spam, executed just a few times for QA.

I tested all edge cases on multiple repositories: adding a category when issues were synced, renaming a category, deleting category. Creating and updating issues when categories were changed.

An example workflow: https://github.com/korrrba/devpool-directory/actions/runs/6772970830/job/18406730058

Tested changes commits:

https://github.com/ubiquity/devpool-directory/commit/bc0abcdd3b469f9081f7873f65ee86eb1a86ad7c
https://github.com/ubiquity/devpool-directory/commit/c5167326a198c71d7cea698576db5094651bfa2c
https://github.com/ubiquity/devpool-directory/commit/f8c35c50df9e4e99e8c66a0e8ebaf1791563caa4

An example screenshot with categories (top most issue from my fork with a category).

![Screenshot from 2023-11-06 16-32-57](https://github.com/ubiquity/devpool-directory-bounties/assets/88761781/61b0dea0-84eb-4b96-b7a2-2443cd2ead2f)

FYI @pavlovcik @rndquu

**Comment by gitcoindev** [comment]
Thank you for approving and merging!
