### ISSUE TITLE
Close Assigned Issues

### ISSUE THREAD

**Issue by 0x4007** [devpool-directory/devpool-directory-tasks#23]
We do not want assigned issues to render on work.ubq.fi 

The simple solution would be to close them (that way they would not be categorized as an "open" task)

The more complex solution would be to have special logic in the UI for the `unavailable` label but I feel that closing as not planned might be better? Then we can close as complete if it is actually closed as complete? 

> > However, the original issue was resolved according to the spec here and that was just to remove the `unavailable` bounties from the devpool repo was it not? 
> 
> You're right. I read the following as "closing" the issue which means that it would not render in the work.ubq.fi UI
> 
> > if bounty is unavailable (i.e. assigned to some bounty hunter) and exists in the list with the state open then close such bounty
> 
> With an emphasis on 
> 
> > then close such bounty
> 
> So we need to file a new issue and get a new pull request to actually close them?

_Originally posted by @pavlovcik in https://github.com/ubiquity/devpool-directory-bounties/issues/11#issuecomment-2017567237_

**Comment by Keyrxng** [comment]
see https://github.com/ubiquity/devpool-directory-bounties/issues/11#issuecomment-2017595979

- rndquu was laying the way for removing the `unavailable` label completely at least that's the direction I was being pushed with hiding the `unavailable` bounties from the devpool

**Comment by 0x4007** [comment]
I don't understand what you're saying but this still remains an active issue. 

This one is on the directory and is currently assigned: https://www.github.com/ubiquity/pay.ubq.fi/issues/196

**Comment by jordan-ae** [comment]
@pavlovcik is this available to work on?

**Comment by Keyrxng** [comment]
@okhot just do `/start` so no one takes it first buddy, this is available tho I was going to grab it myself but gl with it

> I don't understand what you're saying

I was referring to the removal of the `unavailable` labels from the devpool

> The more complex solution would be to have special logic in the UI for the unavailable label 

This seems backwards if those labels are being removed

**Comment by jordan-ae** [comment]
@Keyrxng thanks

**Comment by jordan-ae** [comment]
Didn't notice I got assigned the other bounties 😅. Thanks I'll pass on this one

**Comment by gentlementlegen** [comment]
@pavlovcik Wouldn't it be easier to have this handled directly via the fetching step inside of `work.ubq.fi`? Seems more like a visual change with filtering rather than changing logic inside of here.

**Comment by 0x4007** [comment]
> The simple solution would be to close them (that way they would not be categorized as an "open" task)

Seems more intuitive for me to implement across all tooling that interacts with the data, which includes the statistics calculation json within this repo that is intended to be displayed on ubq.fi

I don't feel that the unavailable label is the right approach

**Comment by Ekep-Obasi** [comment]
Hi @Keyrxng, I'd like to give this a shot

**Comment by gentlementlegen** [comment]
> > The simple solution would be to close them (that way they would not be categorized as an "open" task)
> 
> Seems more intuitive for me to implement across all tooling that interacts with the data, which includes the statistics calculation json within this repo that is intended to be displayed on ubq.fi
> 
> I don't feel that the unavailable label is the right approach

If for some reason tomorrow we wanted to display these tasks and add a sorting parameter about them, we should revert this. To me it comes as simple as filtering out issues that have an assignee, which is straightforward and requires only one line of code change in `work.ubq.fi`

Edit: I noticed in the devpool that no one is assigned on the issues, which doesn't allow for sorting by assignee. Maybe actually assigning someone to the issues could be a solution, so we can directly sort using GitHub API?

**Comment by 0x4007** [comment]
It's not possible unless they are added to the org/repo as a collaborator I already looked into that. Please let's just go with the spec.

**Comment by 0x4007** [comment]
> /start

You need to set your wallet address @Ekep-Obasi 

Also for obvious reasons we don't allow people to make multiple GitHub accounts just to get around assign limits. You will be unassigned if things aren't getting done in time. 

In addition if anybody frontruns the delivery on this I would credit them as this is an emergency task

**Comment by Keyrxng** [comment]
Would that be bad karma for the frontrunner? 😂

**Comment by gitcoindev** [comment]
> we don't allow people to make multiple GitHub accounts just to get around assign limits

An interesting concept to game the system, if one can type fast 😂

**Comment by jordan-ae** [comment]
We're not the same person 😅 he's my brother though. We have similar names. It's from the git history that we're different people. Changed my git name to make it less similar

**Comment by 0x4007** [comment]
> Would that be bad karma for the frontrunner? 😂

We don't have it formalized but I think that high priority (emergency) tasks should be free-for-all because we need it done at any costs, figuratively speaking.

**Comment by rndquu** [comment]
@pavlovcik This feature (if partner issue is assigned then it will be closed in devpool) is already implemented, we see assigned issues at https://work.ubq.fi/ because of https://github.com/ubiquity/devpool-directory-bounties/issues/22

**Comment by 0x4007** [comment]
> @pavlovcik This feature (if partner issue is assigned then it will be closed in devpool) is already implemented, we see assigned issues at https://work.ubq.fi/ because of #22

I'm at the conference so I can't efficiently handle novel situations. What should we do here?

**Comment by Keyrxng** [comment]
> What should we do here?

- https://github.com/ubiquity/devpool-directory/pull/1159 this aims to take care of things

**Comment by 0x4007** [comment]
@rndquu would you be able to address this?

**Comment by rndquu** [comment]
> @rndquu would you be able to address this?

Already addressed in https://github.com/ubiquity/devpool-directory/pull/1159 and https://github.com/ubiquity/devpool-directory/pull/1158

**Comment by Keyrxng** [comment]
@rndquu should this be closed as not-planned then considering it's already been handled by yourself and in my test coverage PR? 

And a new issue should be opened for improving test coverage specifically, or should this be closed as complete with the merging of my PR?
