### ISSUE TITLE
`.gitignore` statistics json

### ISSUE THREAD

**Issue by 0x4007** [devpool-directory/devpool-directory-tasks#24]
- gitignore will solve issues with merge conflicts
- this will hide it from the files view https://docs.github.com/en/repositories/working-with-files/managing-files/customizing-how-changed-files-appear-on-github

**Comment by 0x4007** [comment]
> /wallet 0x2F05fD58023B0a95d1866aa0A3b672cEf05945c5

@gentlementlegen Would you mind manually registering them into the database while we look for a fix? This will allow them to collect their rewards so it's urgent.

**Comment by gentlementlegen** [comment]
@pavlovcik Will manually add them. Error still seems to be `No EVM private key found` from the logs.

**Comment by gentlementlegen** [comment]
@jordan-ae Could you please try again to query the bot? I tried to manually register you in the database, hopefully fixes your issue.

**Comment by jordan-ae** [comment]
@pavlovcik havent been able to claim this. I'm using brave as brower. When I to claim it just says Claiming and no matter how long I wait the state doesnt change

**Comment by 0x4007** [comment]
I use brave and metamask. Can you try claiming with metamask wallet? 

If there's an error with brave wallet can you file an issue?

**Comment by jordan-ae** [comment]
@pavlovcik When I use metamask. Here's the response
![image](https://github.com/ubiquity/devpool-directory-bounties/assets/33989423/74d310ea-fde9-4777-b125-2430da1429a0)

**Comment by 0x4007** [comment]
I get this occasionally too. I think it's related to internet connectivity. I don't know the root problem yet

**Comment by jordan-ae** [comment]
Okay I see I'd been trying for a while now. Had already given up. On Brave browser it doesn't even throw an error it just loads for ever.
