### ISSUE TITLE
Duplicate Bug

### ISSUE THREAD

**Issue by 0x4007** [devpool-directory/devpool-directory-tasks#26]
There's a duplicate that doesn't work. I am assuming it is related to transferring the issue to another repository, although I am not 100% sure what the root cause is.

I think that we should watch out for this situation in the script that mirrors the issues. Either it should be able to edit the issue body (the pointer link) or it should delete itself.

Last suggestion is to simply compare issue bodies and if any are redundant, to delete the newer, duplicate issue.

![3331b0ea devpool-directory-ui pages dev_](https://github.com/ubiquity/devpool-directory-bounties/assets/4975670/3b969cfc-1bcd-4a36-abca-33c99f1e5033)

The duplicates in question in the directory:

1. https://github.com/ubiquity/devpool-directory/issues/1055
2. https://github.com/ubiquity/devpool-directory/issues/1179

> Moving the task to the new https://github.com/ubiquibot/conversation-rewards as it is more relevant there.

_Originally posted by @gentlementlegen in https://github.com/ubiquibot/conversation-rewards/issues/22#issuecomment-2107334024_

**Comment by 0x4007** [comment]
I think this is cache related. We should stress test our cache to fix problems like this.

**Comment by rndquu** [comment]
Right now there're no any duplicated issues + cache system has been [updated](https://github.com/ubiquity/work.ubq.fi/pull/104) recently, perhaps it makes sense to close current issue as "not planned" and reopen in case we encounter this bug again.
