### ISSUE TITLE
Remove `Unavailable` lable

### ISSUE THREAD

**Issue by rndquu** [devpool-directory/devpool-directory-tasks#27]
Check [this](https://github.com/ubiquity/devpool-directory/issues/985) issue.

You may see that `ubiquibot` regularly adds and immediately removes the `Unavailable` label in the issue which is a sort of spamming.

<img width="1512" alt="Screenshot 2024-06-08 at 09 32 26" src="https://github.com/ubiquity/devpool-directory-bounties/assets/119500907/f1d7dd4e-3262-44b2-a799-5af3126a4f21">

We decided to get rid of the `Unavailable` label so it makes sense to remove all related logic in the code.

**Comment by 0x4007** [comment]
> /start
> 
> 

@gentlementlegen  why it doesn't work

**Comment by gentlementlegen** [comment]
@0x4007 It seems that when a carriage return is in the body, it gets stripped on display by GitHub but is not recognized as a command by the kernel. I my two commands above I used:
```
/start
```
and
```
/start

```

The latter one should be valid as well.

**Comment by 0x4007** [comment]
Okay so preprocess all prospective command comments with `.trim()`

**Comment by 0x4007** [comment]
I think this no longer is a problem.
