### ISSUE TITLE
Completed & Assigned Double Count in Analytics 

### ISSUE THREAD

**Issue by 0x4007** [devpool-directory/devpool-directory-tasks#29]
According to the report, we have 173 tasks currently being worked on. I have a feeling its double counting the completed and assigned metrics. Another red flag is the dollar amount of projects being worked on right now ($25821) 

Please verify that this is correct. 

https://github.com/ubiquity/devpool-directory/blob/178460b549838e11e52c1d40763e656c5924a05b/total-rewards.json
```json
{
  "rewards": {
    "notAssigned": 5724,
    "assigned": 25821,
    "completed": 52788,
    "total": 84333
  },
  "tasks": {
    "notAssigned": 24,
    "assigned": 173,
    "completed": 457,
    "total": 654
  }
}
```

**Comment by 0x4007** [comment]
@Keyrxng perhaps you can take a look. This came to mind because I want to display the analytics on ubq.fi for our marketing purposes, and as I started working on it I realized the numbers looked off.

**Comment by Keyrxng** [comment]
@0x4007 how should the `opt.out` be handled in in terms of stats, should they also be excluded?

This is how it looks with them excluded and removing an unnecessary  call to `labels.some()` 

```ts
rewards: { 
  notAssigned: 6299, 
  assigned: 4450, 
  completed: 34100, 
  total: 44849 
},
tasks: { 
  notAssigned: 23, 
  assigned: 18, 
  completed: 261, 
  total: 302 
}
```

Maybe exclude the open and assigned tasks from the counts if `opt.out` but keep in the completed figures I think this makes sense and looks good

```ts
rewards: {
  notAssigned: 6299,
  assigned: 4450,
  completed: 53238,
  total: 63987
},
tasks: {
  notAssigned: 23,
  assigned: 18,
  completed: 459,
  total: 500
}
```

**Comment by 0x4007** [comment]
<img width="1317" alt="image" src="https://github.com/ubiquity/devpool-directory-bounties/assets/4975670/58f8428d-7090-4568-aead-ba5fbc03b64c">
👍👍

**Comment by Keyrxng** [comment]
beautiful
