### ISSUE TITLE
Sync priority and time labels

### ISSUE THREAD

**Issue by rndquu** [devpool-directory/devpool-directory-tasks#3]
Right now only the `Price` label is synced. We should also sync `Priority` and `Time` labels from partners' issues.

### Edit 31 Aug 

- [x] Please sync all labels, intended to describe the type of task it is (Solidity, UI/UX etc)
- [x] disable `assistive-pricing` on the repo so that the bot doesn't try to price the sync'd priority and time labels.

**Comment by 0x4007** [comment]
I think we should sync everything, including the type of task (Solidity, UI/UX etc) this provides useful context to new bounty hunters jumping in. Would you also be able to handle this after 

- #9

**Comment by 0x4007** [comment]
I tried generating the permit but your last comment was over a week ago and there is a bug preventing me from leaving you assigned in this case.
