### ISSUE TITLE
Issue auto-response

### ISSUE THREAD

**Issue by Keyrxng** [devpool-directory/devpool-directory-tasks#36]
When I just started contributing I made [this same mistake](https://github.com/ubiquity/devpool-directory/issues/1402) and it was never picked up by the team.

It would be great if we could have an automatic response from the bot when someone comments on any issue in the `devpool-directory`. This message would be something like `This is a no-reply repo, please visit ${taskUrl} to contribute towards this task.`

We should automate this so that we can set-and-forget which is the best way to handle this.

**Comment by 0x4007** [comment]
Well I have a dedicated app for the directory. We can make a super simple standalone Cloudflare worker and point the webhook to it. It's a one off and we don't need to make it more complicated than it needs to be.

**Comment by 0x4007** [comment]
Moved to https://github.com/ubiquibot/plugins-wishlist/issues/44
