### ISSUE TITLE
Twitter Posting Bug

### ISSUE THREAD

**Issue by jordan-ae** [devpool-directory/devpool-directory-tasks#37]
Noticed that during some syncs, all issues are reposted to Twitter as  recently created issues. Haven't done much digging into but it happens fairly often I think we should look into it

![Screenshot from 2024-08-29 16-14-52](https://github.com/user-attachments/assets/db17a5a3-f059-4e6f-8a2d-0a142829005a)

**Comment by 0x4007** [comment]
I reinitialized the directory. This won't be an issue moving forward.
