### ISSUE TITLE
Refactor Statistics

### ISSUE THREAD

**Issue by Keyrxng** [devpool-directory/devpool-directory-tasks#41]
Related to #27 

Right now the statistics are based on the collection of issues within the devpool. The `Unavailable` label is pretty central to how things are currently calculated

```ts
// devpool issue has unavailable label because it's assigned and so it's closed
const isAssigned = labels.find((label) => (label.name as string).includes(LABELS.UNAVAILABLE)) && issue.state === "closed";
// devpool issue doesn't have unavailable label because it's unassigned and closed so it's merged therefore completed
const isCompleted = !labels.some((label) => (label.name as string).includes(LABELS.UNAVAILABLE)) && issue.state === "closed";
```

The logic of the devpool dictates that any partner-assigned task will be closed upon assignment and only re-opened if it's priced and unassigned. Without the `Unavailable` label to indicate this for us we have a couple of options:

- We could close devpool issues as `not_planned` while they are assigned instead, closing as `complete` once paid out.
- We could simply use the partner issues. My approach builds a partner project Map on entry and we pass that to stats etc.

Some problems with those approaches:

- We'd need to author a script to update all devpool issues open and closed. Some issues remain assigned even after completion so we'd need to include additional logic to account for this.
- Partner issue is obv a good source of data but it's in the partner' hands not ours. If they racked up 50k worth of stats and then deleted their org or nuked all of their issues/repos etc we'd lose a chunk of our stats.

I think the best approach is to use the partner tasks directly although it comes with strings:

- We persist our data better. Like a snapshot each month and store a timeline of stats which in the case of the above scenario we can recover easily. (Yeah we have git commit history but with 24 commits a day I don't think it's ideal. Plus with any changes to how stats etc are calculated it's far easier to audit.)
- Use a combination of partner tasks and our devpool issues to validate `open/assigned/completed`

---

The Stats themselves, big numbers and all that ;) but we have some grey areas I think. So we capture `open, assigned, completed` and we also have a bunch of repos excluded. 

- Should we exclude those same repos from all stat calculations or they should be added to the total only?
- Tasks which are re-opened, should they be considered to be completed since it's been paid out or should they fall into `open/assigned`?
- `completed` is considered to be what? partner task closed as `completed` and is currently closed (may not have a PR associated so we should not rely on that as a check)
- Should we capture `reopened` or another similar category? (internal audit likes this)

##### I'm refactoring tests for this right now and will PR soon

**Comment by Keyrxng** [comment]
rfc @rndquu @0x4007

**Comment by Keyrxng** [comment]
A separate couple of questions:

- Should we remove all of the tasks from the devpool which belong to repos that are currently excluded? (150-200)

- If I give you a list of unofficial bot issues that are hiding in the devpool could you delete them please?

- If we exclude the repos from the `open/assigned` stat counts obviously the numbers won't add up, is this an acceptable loss?

**Comment by rndquu** [comment]
@Keyrxng Is https://github.com/ubiquity/devpool-directory/blob/development/devpool-statistics.json accurate right now?

**Comment by Keyrxng** [comment]
No it's still a problem @rndquu. Stats still flickering and the `UNAVAILABLE` label logic is still present and application & removal of the label is still present on closed issues as it was before. It seems less aggressive now but 7hrs ago from this comment is the most recent duplicate application & removal of that label.

@0x4007 has refactored quite a bit it seems so I'm not 100% sure where things stand

**Comment by Keyrxng** [comment]
I just noticed that this issue was closed 3 days ago and the [devpool issue](https://github.com/ubiquity/devpool-directory/issues/1553) is still open, runs are happening but the last time the devpool issue was modified was 3 days ago during a partner label change it seems 

![image](https://github.com/user-attachments/assets/f63ac53c-306b-4af2-a834-0b4560b77fc7)
