### ISSUE TITLE
ID and Partner label mismatch

### ISSUE THREAD

**Issue by Keyrxng** [devpool-directory/devpool-directory-tasks#42]
So it seems that when an issue is transferred to another repository or organization that the issue takes on a new `node_id` so we must update our logic to handle out-of-sync labels.

We should also aim to remove any partner issues that have been deleted (I assume) but still exist within the devpool as they can belong to repos that have been deleted.

Since we already have the `IssueRemover` class we can borrow it and delete any erroneous tasks before we perform any state changes.

I think we should also delete any devpool issues that's body does not match the typical url formatting standard.

**Comment by rndquu** [comment]
If github issue which exists in devpool is transferred from one repo to another then:
1. Issue with the "old" `node_id` (from the old repo) will be closed
2. New issue will be created in the devpool with a new `node_id`

I think it sounds reasonable although not 100% accurate in terms of devpool statistics.

**Comment by Keyrxng** [comment]
> If github issue which exists in devpool is transferred from one repo to another then:
> 
> 1. Issue with the "old" `node_id` (from the old repo) will be closed
> 2. New issue will be created in the devpool with a new `node_id`
> 
> I think it sounds reasonable although not 100% accurate in terms of devpool statistics.

In my implementation I used the `IssueRemover` to delete the invalid task which solves for your scenario re:stats afaik
