### ISSUE TITLE
Make Twitter Secrets Optional

### ISSUE THREAD

**Issue by 0x4007** [devpool-directory/devpool-directory-tasks#49]
I just set up my own instance for QA and filled in nonsense values for the Twitter related secrets and it worked. We just need to properly handle, if no Twitter secrets are found, to skip Twitter operations.

**Comment by Atharva-Kanherkar** [comment]
hi @0x4007 I am new here - can you guide me on how to start, so i can begin? Like solving small issues like these would be very learning. Just guide me where I can study about whole of the codebase and where should I start.
