### ISSUE TITLE
Already Assigned Issues in Devpool

### ISSUE THREAD

**Issue by jordan-ae** [devpool-directory/devpool-directory-tasks#54]
Several issues that have already been assigned are still appearing as available tasks in the [work.ubq.fi](https://work.ubq.fi/) platform. Here are a couple examples:

 [Create UI for UbiquityPool - Issue #1](https://github.com/ubiquity/uusd.ubq.fi/issues/1)
    [Generalized "GitHub Webhook + Contributor Role -> Rewards" No Config v1 - Issue #46](https://github.com/ubiquity-os/plugins-wishlist/issues/46)
    [Collaborator Gating Based On Label- Issue #62](https://github.com/ubiquity-os-marketplace/command-start-stop/issues/62)
    [First Assignment  - Issue #6](https://github.com/ubiquity-os-marketplace/ubiquity-os-kernel-telegram/issues/6)
    [Toy "Demo" Illustrating the Flow - Issue #29](https://github.com/ubiquity/ubq.fi/issues/29)
    [Pull Precheck - Issue #45](https://github.com/ubiquity-os/plugins-wishlist/issues/45)
    [Ubiquity Banking On-Ramp Experience (*.eth -> UUSD.gno) - Issue #4](https://github.com/ubiquity/uusd.ubq.fi/issues/4)

**Comment by Keyrxng** [comment]
The devpool-directory backend is broken right now and the org is aware of this @jordan-ae ty

Good to see you back buddy

**Comment by 0x4007** [comment]
I refactored the backend logic but introduced this bug. We just need to 

1. filter out unavailable tasks from the UI
2. Match their closed state
