### ISSUE TITLE
Default Colors

### ISSUE THREAD

**Issue by 0x4007** [devpool-directory/devpool-directory-tasks#7]
https://github.com/ubiquity/ubiquibot/issues/315

**Comment by rndquu** [comment]
This issue implies that price labels should be green while other labels should be gray. As far as I understand label colors already have correct values [here](https://github.com/ubiquity/devpool-directory/issues) so it seems that we can close this issue.

**Comment by 0x4007** [comment]
No I manually changed the color of the existing labels using my tool https://github.com/ubiquity/github-labels-processor

When new labels are created, they will be created with the wrong colors.
