### ISSUE TITLE
Display Currently Available Bounties

### ISSUE THREAD

**Issue by 0x4007** [devpool-directory/devpool-directory-tasks#8]
We should have a filter that indicates the current assignment status of a bounty. This way, bounty hunters can filter the view for only available bounties. It could be annoying and tedious if all the bounties they are interested in handling are taken. It takes a few clicks right now to view the status of the bounty.

Proposed solutions:

1. Directly assign the assignee in the `devpool-directory` mirror of the issue. This may lead to unnecessary notifications (or not!) but it will be the most direct way to express that the bounty is taken.
2. Add a label on bounties that are currently assigned e.g. `Unavailable`

Both solutions will allow bounty hunters to filter for only available bounties.

**Comment by harjaapdhillon16** [comment]
https://github.com/ubiquity/devpool-directory/pull/660 Raised a PR @pavlovcik

**Comment by 0x4007** [comment]
> [ubiquity/devpool-directory#660](https://github.com/ubiquity/devpool-directory/pull/660) Raised a PR @pavlovcik

@rndquu I just realized we can't directly associate these pull requests with the issues. Perhaps we should find a better setup for bounty hunters.

**Comment by rndquu** [comment]
> > [ubiquity/devpool-directory#660](https://github.com/ubiquity/devpool-directory/pull/660) Raised a PR @pavlovcik
> 
> @rndquu I just realized we can't directly associate these pull requests with the issues. Perhaps we should find a better setup for bounty hunters.

I've updated the description https://github.com/ubiquity/devpool-directory/pull/660#issue-1740674644 and the PR is linked now although this is a "cross repo" PR

**Comment by harjaapdhillon16** [comment]
@pavlovcik Can this issue be closed now , my PR has been approved !
